("inner exception message" "->" ("thrown an exception" "throw" "throwing-func" "try" "func-that-does-not-throw" "try"))
